#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zoom state=floating
bspc rule -a Zathura state=tiled

#
# Autostart
#

# Polkit
/usr/bin/lxsession &
# Bar
$HOME/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Wallpaper
feh --bg-scale Pictures/Wallpapers/spirited-away.jpg &
# Picom
picom -b --experimental-backends &
# Location for Redshift
/usr/lib/geoclue-2.0/demos/agent &
# Blue Light Filter
redshift
# TLP
tlp start
# RClone Drive
rclone mount gdrive: Drive
